name: validation_tool
dependencies:
- backports_abc=0.4=py27_0
- cairo=1.12.18=6
- curl=7.45.0=0
- cycler=0.10.0=py27_0
- cython=0.23.5=py27_0
- flask=0.10.1=py27_1
- fontconfig=2.11.1=5
- freetype=2.5.5=0
- hdf5=1.8.15.1=2
- itsdangerous=0.24=py27_0
- jinja2=2.8=py27_0
- libgfortran=3.0=0
- libnetcdf=4.3.3.1=3
- libpng=1.6.17=0
- libxml2=2.9.2=0
- markupsafe=0.23=py27_0
- matplotlib=1.5.1=np110py27_0
- mkl=11.3.1=0
- netcdf4=1.2.2=np110py27_0
- numpy=1.10.4=py27_1
- openssl=1.0.2g=0
- pandas=0.18.0=np110py27_0
- patsy=0.4.0=np110py27_0
- pip=8.1.1=py27_1
- pixman=0.32.6=0
- psycopg2=2.6.1=py27_1
- pycairo=1.10.0=py27_0
- pyparsing=2.0.3=py27_0
- pyqt=4.11.4=py27_1
- python=2.7.11=0
- python-dateutil=2.5.1=py27_0
- pytz=2016.2=py27_0
- qt=4.8.7=1
- readline=6.2=2
- scipy=0.17.0=np110py27_2
- setuptools=20.3=py27_0
- singledispatch=3.4.0.3=py27_0
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- sqlalchemy=1.0.12=py27_0
- sqlite=3.9.2=0
- ssl_match_hostname=3.4.0.2=py27_0
- statsmodels=0.6.1=np110py27_0
- tk=8.5.18=0
- werkzeug=0.11.4=py27_0
- wheel=0.29.0=py27_0
- xarray=0.7.2=py27_0
- zlib=1.2.8=0
- pip:
  - autopep8==1.2.2
  - backports-abc==0.4
  - backports.ssl-match-hostname==3.4.0.2
  - decorator==4.0.9
  - geoalchemy2==0.2.6
  - ipdb==0.9.0
  - ipython==4.1.2
  - ipython-genutils==0.1.0
  - path.py==8.1.2
  - pep8==1.7.0
  - pexpect==4.0.1
  - pickleshare==0.6
  - ptyprocess==0.5.1
  - pyflakes==1.1.0
  - pygeobase==0.3.9
  - pygeogrids==0.1.9
  - pykdtree==1.1.1
  - pyproj==1.9.5.1
  - pytesmo==0.4.0
  - simplegeneric==0.8.1
  - traitlets==4.2.1

